cache_size_mb: 0

# Database configuration. This can also be a list of PG configs.
postgres:
  # Database connection string. You can use env vars too, for example:
  #   $DATABASE_URL
  #   ${DATABASE_URL:-postgresql://postgres@localhost/db}
  connection_string: ${DATABASE_URL}

  # # Same as PGSSLCERT for psql
  # ssl_cert: './postgresql.crt'
  # # Same as PGSSLKEY for psql
  # ssl_key: './postgresql.key'
  # # Same as PGSSLROOTCERT for psql
  # ssl_root_cert: './root.crt'

  # #  If a spatial table has SRID 0, then this SRID will be used as a fallback
  # default_srid: 4326

  # # Maximum Postgres connections pool size [default: 20]
  # pool_size: 20

  # # Limit the number of table geo features included in a tile. Unlimited by default.
  # max_feature_count: 1000

  # # Control the automatic generation of bounds for spatial tables [default: quick]
  # # 'calc' - compute table geometry bounds on startup.
  # # 'quick' - same as 'calc', but the calculation will be aborted if it takes more than 5 seconds.
  # # 'skip' - do not compute table geometry bounds on startup.
  # auto_bounds: skip

  # # Enable automatic discovery of tables and functions.
  # # You may set this to `false` to disable.
  # auto_publish: false

  # Associative arrays of table sources
  tables:
    railway_line_casing:
      schema: public
      table: railway_line_casing
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        usage: string
        service: string
        construction: string
        construction_railway: string

    railway_line_low:
      schema: public
      table: railway_line_low
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        usage: string
        service: string
        construction: string
        construction_railway: string
        rank: string
        pzb: string
        lzb: string
        atb: string
        atb_eg: string
        atb_ng: string
        atb_vv: string
        atc: string
        scmt: string
        asfa: string
        kvb: string
        tvm: string
        etcs: string
        construction_etcs: string
        ptc: string
        zsi127: string

    railway_line_med:
      schema: public
      table: railway_line_med
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        usage: string
        service: string
        construction: string
        construction_railway: string
        rank: string
        pzb: string
        lzb: string
        atb: string
        atb_eg: string
        atb_ng: string
        atb_vv: string
        atc: string
        scmt: string
        asfa: string
        kvb: string
        tvm: string
        etcs: string
        construction_etcs: string
        ptc: string
        zsi127: string

    railway_line_fill:
      schema: public
      table: railway_line_fill
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        usage: string
        service: string
        construction: string
        construction_railway: string
        rank: string
        pzb: string
        lzb: string
        atb: string
        atb_eg: string
        atb_ng: string
        atb_vv: string
        atc: string
        scmt: string
        asfa: string
        kvb: string
        tvm: string
        etcs: string
        construction_etcs: string
        ptc: string
        zsi127: string

    railway_signals:
      schema: public
      table: railway_signals
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        ref: string
        feature: string
        departure_form: string
        main_form: string
        main_repeated_states: string
        speed_limit_form: string
        speed_limit_states: string
        main_height: string
        shunting_form: string
        distant_form: string
        humping_form: string
        train_protection_shape: string
        train_protection_form: string
        train_protection_type: string
        deactivated: string

    signal_boxes_point:
      schema: public
      table: signal_boxes_point
      srid: 3857
      geometry_column: way
      geometry_type: POINT

    signal_boxes_polygon:
      schema: public
      table: signal_boxes_polygon
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON

    signal_boxes_text:
      schema: public
      table: signal_boxes_text
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        ref: string
        name: string

    prorail_lichtseinen:
      schema: public
      table: prorail_lichtseinen
      srid: 3857
      geometry_column: wkb_geometry
      # id_column: ogc_fid
      #minzoom: 0

      # An integer specifying the maximum zoom level. MUST be >= minzoom
      #maxzoom: 30

      # The maximum extent of available map tiles. Bounds MUST define an area
      # covered by all zoom levels. The bounds are represented in WGS:84
      # latitude and longitude values, in the order left, bottom, right, top.
      # Values may be integers or floating point numbers.
      # bounds: [-180.0, -90.0, 180.0, 90.0]

      # Tile extent in tile coordinate space
      # extent: 4096

      # Buffer distance in tile coordinate space to optionally clip geometries
      # buffer: 64

      # Boolean to control if geometries should be clipped or encoded as is
      # clip_geom: true

      # Geometry type
      geometry_type: GEOMETRY

      # List of columns, that should be encoded as tile properties (required)
      properties:
        naam: string

  # Associative arrays of function sources
  functions:
    function_zxy_query:
      schema: public
      function: function_zxy_query
      # minzoom: 0
      # maxzoom: 30

fonts:
  - /config/fonts
